openapi: 3.0.0

info:
  version: "0.0.1-SNAPSHOT"
  title: Api-Leo

tags:
  - name: "Employees"
    description: "Provides enpoints to view and manage Employees"
  - name: "Departments"
    description: "Provides enpoints to view and manage Departments"

servers:
  - url: "http://127.0.0.1:8080/"
    description: "Local host environment"

paths:
  /colaborador/paginacaoa:
    get:
      operationId: "listarColaboradores"
      tags:
        - "Employees"
      description: "Find employees with type A of pagination."
      parameters:
        - in: "query"
          name: "page"
          description: "Page number you want to see when the data is fetched."
          required: true
          type: int
        - in: "query"
          name: "qtd"
          description: "Quantity of results per page."
          required: true
          type: int
        - in: "query"
          name: "ordination"
          description: "How to order the results: asc or desc"
          required: false
          type: String
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Colaborador'
        400:
          description: "Something went wrong with your request"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: "The user doesn't have permissions to read"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Colaborador:
      type: object
      properties:
        label:
          type: string
        value:
          type: string
      required:
        - label
        - value

    ErrorResponse:
      type: object
      properties:
        message:
          type: string

#TODO finalize
