openapi: 3.0.0

info:
  version: "0.0.1-SNAPSHOT"
  title: Api-Leo
  description: "This is a simple specification of a business who manages some employees and departments"
  termsOfService: "http://leoduarte.dev/terms"
  contact: "leonardoduarte1305@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: "Employees"
    description: "Provides enpoints to view and manage Employees"
  - name: "Departments"
    description: "Provides enpoints to view and manage Departments"

#host: "leoduarte.dev/business"
#basePath: "/"
#schemes:
#  - "http"
#  - "https"
servers:
  - url: "http://127.0.0.1:8080/"
    description: "Local host environment"

paths:
  /colaborador/paginacaoa:
    get:
      tags:
        - "Employees"
      summary: "Find all employees"
      description: "Find employees with type A of pagination."
      operationId: "listarColaboradores"
      produces:
        - "application/json"
      parameters:
        - in: "query"
          name: "page"
          description: "Page number you want to see when the data is fetched."
          required: true
          type: int
        - in: "query"
          name: "qtd"
          description: "Quantity of results per page."
          required: true
          type: int
        - in: "query"
          name: "ordination"
          description: "How to order the results: asc or desc"
          required: false
          type: String
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Colaborador'
        400:
          description: "Something went wrong with you request"
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'
        403:
          description: "The user doesn't have permissions to read"
          content:
            application/json:
              schema:
                $ref: '#/definitions/ErrorResponse'

components:
  schemas:
    Colaborador:
      type: object
      properties:
        name: nome
          description: The employee's name
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string

#TODO finalize
